name: Generate metrics
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
  push:
    branches: [main]
concurrency:
  group: metrics
  cancel-in-progress: false
permissions:
  contents: write
jobs:
  metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: tu11aa
          filename: metrics.svg
          base: header, activity
          config_timezone: Asia/Ho_Chi_Minh
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
